trigger: 
- '*''

pool: 
  vmImage: ubuntu-latest

steps: 
- task: UsePythonversion@0
  inputs: 
    versionSpec: '3.7'
  displayName: 'Use Python version 3.7'

- script: 
    python -m pip install --upgrade pip
  displayName: 'Upgrade pip'

- script: 
    pip install -r requirements.txt
  displayName: 'Install dependencies'