trigger: 
- '*'

pool: 
  vmImage: ubuntu-latest

steps: 
- task: UsePythonversion@0
  inputs: 
    versionSpec: '3.6'
  displayName: 'Use Python version 3.6'

- script: 
    python -m pip install --upgrade pip
  displayName: 'Upgrade pip'

- script: 
    conda env create -f 'environment.yml'
  displayName: 'Set up environmnt'

- script: 
    conda activate py365-mlops
  displayName: 'Set up environmnt'